# Site settings
title: DraySec
email: drayman@pm.com
url: https://drayman.kulturdroge.de
description: "Just another blog about security"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Made with heart

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/
  - title: github
    url: https://github.com/

# Build settings
markdown: kramdown
permalink: pretty
