# Site settings
title: Drayman's Blog
email: drayman@pm.com
url: http://drayman.online
description: "Just another blog about security"
logo: /assets/images/logo.jpg
footer: "W.I.P"
github_username: thedrayman
author: drayman

# Build settings
markdown: kramdown

# GitHub pages settings
repository: thedrayman/thedrayman.github.io

# Theme settings
theme: jekyll-theme-minimal
paginate: 5
paginate_path: /page:num/
permalink: /:categories/:title/
