# Site settings
title: Drayman's Blog
email: drayman@pm.com
url: http://drayman.online
description: "Just another blog about security"
# logo: /assets/images/logo.jpg
footer: "W.I.P"
github_username: thedrayman

# Build settings
markdown: kramdown
plugins:
  - jekyll-font-awesome-sass

# GitHub pages settings
repository: thedrayman/thedrayman.github.io

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.14.1"
paginate: 5
paginate_path: /page:num/
permalink: /:categories/:title/


