# Site settings
title: Drayman's Home
email: drayman@pm.com
url: http://drayman.online
description: ""
github_username: thedrayman
repository: thedrayman/thedrayman.github.io

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.16.2"
minimal_mistakes_skin : "dirt"
paginate: 5
paginate_path: /page:num/
permalink: /:categories/:title/

# Site Author
author:
  name             : "Fabian Froelich"
  avatar           : /assets/images/myself.jpg
  bio              : "Just another guy talking about computer science and IT security"
  location         : "Kassel, Germany"
  links:
    - label: "drayman@pm.com"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:drayman@pm.com
    - label: "Draymans home"
      icon: "fas fa-fw fa-link"
      url: "https://drayman.online"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/thedrayman"
      
# Reading Files
include:
  - _pages