# Site settings
title: Drayman's Blog
email: drayman@pm.com
url: http://drayman.online
description: ""
#logo: /assets/images/logo.jpg
footer: "still w.i.p. but with <3"
github_username: thedrayman

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# GitHub pages settings
repository: thedrayman/thedrayman.github.io

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.16.2"
minimal_mistakes_skin : "dirt"
paginate: 5
paginate_path: /page:num/
permalink: /:categories/:title/

# Site Author
author:
  name             : "Drayman"
  avatar           : /assets/images/logo.jpg
  bio              : "Just another opinion about computer science and IT security"
  location         : "Kassel, Germany"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:drayman@pm.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://drayman.online
    #- label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/thedrayman"
    - label: "Keybase"
      icon: "fab fa-fw fa-keybase"
      url: "https://keybase.io/"
    - label: "W.I.P."
      icon: "fas fa-fw fa-key"
      url: ""
      
# Reading Files
include:
  - _pages