# Site settings
title: Drayman's Blog
email: drayman@pm.com
url: http://drayman.online
description: "Just another blog about security"
github_username: thedrayman

# Build settings
markdown: kramdown

# GitHub pages settings
repository: thedrayman/thedrayman.github.io

# Theme settings
theme: jekyll-theme-minimal
paginate: 5
paginate_path: /page:num/
permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true

author:
  name: "Florian Euchner"
  avatar: "/assets/images/avatar.png"
  bio: "EE Student @ University of Stuttgart"
  location: "Nürtingen, Germany"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Jeija"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://youtube.com/Jeija"
    - label: "Hacker News"
      icon: "fab fa-fw fa-hacker-news-square"
      url: "https://news.ycombinator.com/user?id=Jeija"
    - label: "jeija@jeija.net"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:jeija@jeija.net"
    - label: "Keybase"
      icon: "fab fa-fw fa-keybase"
      url: "https://keybase.io/Jeija"
    - label: "E68B 959D 5578 1895"
      icon: "fas fa-fw fa-key"
url: ""

