# Site settings
title: Drayman's Blog
email: drayman@pm.com
url: http://drayman.online
description: ""
#logo: /assets/images/logo.jpg
footer: "W.I.P"
github_username: thedrayman

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# GitHub pages settings
repository: thedrayman/thedrayman.github.io

# Theme settings
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.16.2"
minimal_mistakes_skin : "dark"
paginate: 5
paginate_path: /page:num/
permalink: /:categories/:title/

# Site Author
author:
  name             : "Drayman"
  avatar           : /assets/images/logo.jpg
  bio              : "Just another blog about security"
  location         : "Kassel, Germany"
  email            :  "me@you.de"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:me@you.de
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
    - label: "Keybase"
      icon: "fab fa-fw fa-keybase"
      url: "https://keybase.io/"
    - label: "W.I.P."
      icon: "fas fa-fw fa-key"
      url: ""